remote-theme: "mmistakes/minimal-mistakes"
name: Ruud de Jong
url: https://rhjdjong.github.io
title: Ruud de Jong
description: Random notations
header_pages:
  - index.md
  - about.md
plugins:
  - jekyll-include-cache
  
